# Generated by Django 5.2 on 2026-07-13 13:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TerminalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('t', 'Train'), ('p', 'plane'), ('b', 'bus')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TripsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('destination_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripdestination', to='tripsapp.terminalmodel')),
                ('origin_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triporigin', to='tripsapp.terminalmodel')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripsapp.vehiclemodel')),
            ],
        ),
        migrations.CreateModel(
            name='TripSeatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'available'), ('r', 'reserved'), ('b', 'book')], default='A')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripsapp.seatmodel')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripsapp.tripsmodel')),
            ],
        ),
        migrations.AddField(
            model_name='seatmodel',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripsapp.vehiclemodel'),
        ),
        migrations.CreateModel(
            name='VehicleSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=100)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripsapp.vehiclemodel')),
            ],
        ),
    ]
