# Generated by Django 5.2 on 2026-07-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='capacity',
        ),
        migrations.AddConstraint(
            model_name='seatmodel',
            constraint=models.UniqueConstraint(fields=('vehicle', 'number'), name='unique_seat_number_per_vehicle'),
        ),
    ]
