# Generated by Django 5.2 on 2026-07-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripsapp', '0002_remove_vehiclemodel_capacity_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tripseatmodel',
            constraint=models.UniqueConstraint(fields=('trip', 'seat'), name='unique_seat_number_per_trip'),
        ),
    ]
