# Generated by Django 5.2 on 2026-07-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripsapp', '0003_tripseatmodel_unique_seat_number_per_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='capacity',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tripseatmodel',
            name='status',
            field=models.CharField(choices=[('A', 'available'), ('b', 'book')], default='A'),
        ),
    ]
