# Generated by Django 5.2 on 2026-07-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripsapp', '0004_vehiclemodel_capacity_alter_tripseatmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='type',
            field=models.CharField(choices=[('t', 'Train'), ('a', 'Airplane'), ('b', 'bus')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='vehiclesectionmodel',
            constraint=models.UniqueConstraint(fields=('row', 'vehicle'), name='unique_row_per_vehicle'),
        ),
    ]
