# Generated by Django 5.2 on 2026-07-15 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripsapp', '0005_alter_vehiclemodel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatmodel',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='tripsapp.vehiclemodel'),
        ),
    ]
