# Generated by Django 5.2 on 2026-07-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripsapp', '0006_alter_seatmodel_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripseatmodel',
            name='status',
            field=models.CharField(choices=[('A', 'available'), ('b', 'booked')], default='A'),
        ),
    ]
