# Generated by Django 5.2 on 2026-07-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsapp', '0001_initial'),
        ('tripsapp', '0007_alter_tripseatmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='tripseat',
            field=models.ManyToManyField(related_name='tripseatorder', to='tripsapp.tripseatmodel'),
        ),
    ]
