# Generated by Django 5.2 on 2026-07-25 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsapp', '0002_ordermodel_tripseat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
