# Generated by Django 5.2 on 2026-07-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsapp', '0003_alter_ordermodel_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='tripseat',
        ),
    ]
